---
- name: Add authorzied key
  hosts: all
  remote_user: root
  tasks:
    - name: Add user authorzied key
      authorized_key:
        user: deploy
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}
