---
- name: Log into private registry
  hosts: all
  remote_user: root
  become: yes
  become_user: deploy
  vars_promt:
    - name: registry
      prompt: "Registry"
      private: no
    - name: username
      prompt: "Username"
      private: no
    - name: password
      prompt: "password"
  tasks:
    - name: Log into private registry
      shell: "docker login -u {{ username }} -p {{ password }} {{ registry }}"
