site:
  ansible-playbook -i hosts.yml site

renew-certificates:
  ansible-playbook -i hosts.yml renew-certificates.yml

authorzie:
  ansible-playbook -i hosts.yml authorzie.yml

docker-login:
  ansible-playbook -i hosts.yml docker-login.yml
